# Generated by Django 6.0.4 on 2026-04-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='statut',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Livré', 'Livré'), ('Annulé', 'Annulé')], default='En cours', max_length=50),
        ),
    ]
