# Generated by Django 6.0.4 on 2026-04-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryproject', '0002_supplier_image_alter_delivery_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
